FROM node:18.14.2-alpine3.17

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Set the NODE_ENV environment variable to "production"
ENV NODE_ENV=staging

# Expose port 3000 to the outside world
EXPOSE 3000

# Start the application
CMD [ "npm", "start" ]