name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [staging, production]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/frontend:latest
          file: Dockerfile.staging

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          # host: ${{ secrets.DROPLET_HOST_${{ matrix.environment | upper }} }}
          # temp change
          host: bayareafilms.org
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo logging in 
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            echo stopping container
            docker stop frontend || true
            echo removing container
            docker rm frontend || true
            echo pulling latest code from docker hub
            docker pull benhalverson/frontend
            echo starting new container
            docker run -d --name frontend -p 80:80 benhalverson/frontend
